"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ReduxProvider from "@/redux/Provider";
import { useState } from "react";
import Cart from "@/components/Cart";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//     title: "E-commerce",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const [showCart, setShowCart] = useState(false);

    return (
        <html lang="en">
            <body className={inter.className}>
                <ReduxProvider>
                    {showCart && <Cart setShowCart={setShowCart} />}
                    <Navbar setShowCart={setShowCart} />
                    {children}
                    <Footer />
                </ReduxProvider>
            </body>
        </html>
    );
}
