export const products = [
    {
        id: 0,
        img: "/products/1.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 1,
        img: "/products/2.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 2,
        img: "/products/3.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 3,
        img: "/products/4.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 4,
        img: "/products/5.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 5,
        img: "/products/6.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 6,
        img: "/products/7.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 7,
        img: "/products/8.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 8,
        img: "/products/9.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 9,
        img: "/products/10.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 10,
        img: "/products/11.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 11,
        img: "/products/12.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 12,
        img: "/products/13.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 13,
        img: "/products/14.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 14,
        img: "/products/15.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
    {
        id: 15,
        img: "/products/16.jpg",
        name: "Lorem",
        price: 41.0,
        category: ["devices"],
        sale: false,
    },
];
